### PR TITLE
[MIG] connector_prestashop_environment: Migration to 16.0

### PR DESCRIPTION
**Pull request by psugne**
https://hive.versada.eu/work_packages/24020

### CODE REVIEW

**Comment by psugne** [comment]
@oerp-odoo note, as I checkout out from OCA 16.0 version, @1c64b0a comes from OCA dir too.

**Comment by oerp-odoo** [comment]
@psugne but OCA 16.0 does not have any modules. Also, I think we should do the other way around here. We should "recreate" our versada branch from OCA 16.0 and merge other branches into it, if it changed from our base and then we should create PR for OCA as well, so eventually when it is merged, we can switch to original.

**Comment by psugne** [comment]
@oerp-odoo :heavy_check_mark:

**Review by oerp-odoo — COMMENTED** [review]
Shouldn't there be original commits for this module?

**Review by oerp-odoo — APPROVED** [review]

**Pull request merged**
